export const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const DEC_ITEM = 'DEC_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const CHANGE_THEME = 'CHANGE_THEME';

//TODO refactor
